### ISSUE TITLE
Similar plug-in for quickfix list

### ISSUE THREAD

**Issue by Konfekt** [msrose/vim-perpetuloc#2]
Perhaps

https://github.com/vim-scripts/QuickFixCurrentNumber

offers some additional inspiration.

**Comment by msrose** [comment]
Thanks @Konfekt, definitely a good thought, although for me personally a quickfix list plugin would be less useful. I might do some research into how to generalize this plugin so that it applies to the quickfix list as well, but it might be a bit trickier since the quickfix list is more of a "global" structure, so there's window jumping to account for. As you suggest, a separate plugin might make more sense.
